### ISSUE TITLE
Create user authentication logic

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#11]
## Info

Create the necessary functions to handle user authentication using the token method. This doesn't need to connect to an API yet. The point of separating the tasks is to make the user logic separate from the REST API, and just have the routes call these functions.

## Tasks

- [ ] Set user password
- [ ] Authenticate user
- [ ] Change password
- [ ] Unit tests

## Tests

- [ ] Should set password
- [ ] Should authenticate user
- [ ] Should change password
