### ISSUE TITLE
Create "Club" model

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#12]
## Info

This model will hold information regarding clubs that signup for the app. It will also store the refresh token used to authenticate with Spotify.

It should have these fields (at least):
- Name
- Refresh token (hash)
- Owner
- Admins

## Tasks

- [ ] Create model
- [ ] Unit tests

## Tests

- [ ] Should create club
- [ ] Should update club
- [ ] Should delete club
