### ISSUE TITLE
Create authentication REST API

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#13]
## Info

This task will require the user authentication logic to be created first. The API will be used by the frontend (and any other future micro-services) to authenticate users. A log out endpoint is not needed since logging in is just activating a token, meaning the frontend would need to handle logging out by deleting the token.

## Tasks

- [x] Login endpoint
- [x] Change password endpoint
- [x] "me" endpoint, returns the info of a logged in user (to check if logged in)
- [ ] Unit tests

## Tests
- [ ] Should log user in
- [ ] Should change password
- [ ] Should return info for logged in user
