### ISSUE TITLE
Create CRUD endpoints for Club model

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#14]
The REST API needs endpoints to Create, Read, Update, and Delete clubs. This will be used by the frontend (and other future micro-services) to manage clubs. 

Logic will be created in the future to secure these routes and only allow certain people to use them.

## Tasks

- [ ] Create club
- [ ] Get club by id
- [ ] Update club
- [ ] Delete club

## Tests

- [ ] Should create club
- [ ] Should get club by id
- [ ] Should update club
- [ ] Should delete club
