### ISSUE TITLE
Track Sync Events

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#40]
## Intro

With the Spotify Web SDK and API, only polling can be used to get updates on current track - potentially sending too many requests to Spotify (and possibly getting charged more). Ideally we should directly communicate with Spotify as little as possible via the API/SDK, under the assumption that each request is charged (free under development mode).

The Web Player, however, uses a web socket connected to Spotify's servers in order to immediately receive updates to current track, allowing the player to react instantaneously to track changes. There are two problems with this:

1. This is only allowed if the track is playing through the web player
3. This is only offered client-side

In order to update the server with the song queue, and other updates regarding the current track, the client player will need to pass these updates to our server via the web socket and send (produce) those events to a Kafka topic to be consumed by the server. 

### Kafka topics:

- `current-track`
    - key: groupId
    - actions: play, pause, next, previous

### Flow

```txt
client (track change)
    ↓
Websocket message
    ↓
Websocket produces Kafka event
    ↓
Server consumes Kafka event
    ↓
Server handles track change event
    ↓
TBD...
```

### Tasks

Create events between client and web socket:
- [x] Play track event
- [x] Pause track event
- [x] Next track event
- [x] Previous track event

Create server consumers:
- [ ] Play track
- [ ] Pause track
- [ ] Next track
- [ ] Previous track

The track queue or state doesn't need to be created, but everything should be in place to create and sync track state in the server.
