### ISSUE TITLE
Tracks Queue

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#48]
## Info

Create a queue service that will manage the order of next tracks. The way we store the track inside a queue item is by storing an object of type `spotify.Track`.

### Big picture stuff

For more info about the functionality surrounding this track, and how it will be used, look at this issue: <https://github.com/ufosc/Jukebox-Server/issues/40>.

We will only use spotify's queue for the next song _only_, instead of using it for the full jukebox queue. This allows us to manage the order of tracks more easily. When the next song plays, the new song at the top of the queue gets sent to the spotify queue via the api. This way spotify can properly preload its information where needed, and can quickly play the song if the skip button were pressed.

## Task

- [ ] Create basic unit tests for main class function
- [ ] Implement queue functions (`server/services/trackQueue.ts`)
- [ ] Ensure the queue file has >= 85% test coverage
