### ISSUE TITLE
Create K8s cluster

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#53]
## Info

This project will use kubernetes (K8s) to run in production. Creating the full production-grade k8s config does not need to be completed in this task, but the backend should properly run.

When getting the images for the deployments, you can use the images used in the `docker-compose.network.yml` file in the [frontend repo](https://github.com/ufosc/Jukebox-Frontend/blob/main/docker-compose.network.yml). These images are automatically pushed to docker hub when changes are pushed to `main` in this repo.

If there is something wrong with one of the images, and you are using Minikube to test the cluster, you can temporarily reference your local docker images - but this will require you to build all of them first and link your environment to Minikube's.

## Task

- [x] Deployment for server
- [ ] Deployment for websocket (keep at 1 replica, another task will be to connect redis backend to account for socket sessions)
- [ ] MongoDB setup (either using deployments & statefulsets, or helm)
- [x] Volume and Volume claim for mongodb
- [x] Proxy deployment
- [x] Config files for environment variables
