### ISSUE TITLE
Search Spotify API

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#64]
## Info

When an admin or a member tries to queue up a track (song), they will want to search spotify in order to choose a certain track. They may want to search by track, album, or artist name.

## Task

- [ ] Create a new `searchTracks` method in the spotify service. Ideally, it should probably take in the spotify credentials to use, and the search query - it shouldn't need to do any communication with the jukebox service, to avoid a circular dependency issue.
  - [ ] Should connect to spotify sdk and search tracks
  - [ ] Returns the tracks it found
- [ ] Create a new api route in the jukebox controller that takes in `jukebox_id` as a param, and allows users to search spotify tracks using the active spotify account saved to the jukebox. 
  - _Note: The user should never be able to see what spotify account is being used, or the credentials of that account. As an example, a club member will search up tracks, but the server will use the spotify account for the club president to make that request, this makes it so the member doesn't have to connect spotify. We may change this in the future if it proves to be a) confusing, or b) a security problem._

**Comment by Ryan-slither** [comment]
I am working on this just need to test.
