### ISSUE TITLE
Jukebox should store current track, even when there's no queue

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Jukebox-Server#70]
## Problem

Club members should be able to see the current track, and next tracks - event when there are no tracks in the queue. Currently, the way the frontend knows about the tracks is via the tracks-queue api and the websocket. 

## Task

- [x] API route for current track
- [x] Store current track in redis
- [x] When tracks-queue api is hit, and there are no tracks in the queue, it should give the tracks in the spotify queue
